### ISSUE TITLE
strlen test issue

### ISSUE THREAD

**Issue by gecarval** [gecarval/42-Luanda-Cursus#1]
@zolambunga o teu strlen pode ser otimizado

**Comment by Caquarta** [comment]
Era bom se o fizesses com apenas 4 ou 5 linhas de código.

**Comment by zolambunga** [comment]
vou tentar ver

**Comment by zolambunga** [comment]
> Era bom se o fizesses com apenas 4 ou 5 linhas de código.

vou fazer em uma apenas...
